# -*- coding: utf-8 -*-
# vim: ft=yaml
---
sudo: required
cache: bundler
language: ruby
dist: xenial

services:
  - docker

# Make sure the instances listed below match up with
# the `platforms` defined in `kitchen.yml`
# NOTE: Please try to select up to six instances that add some meaningful
#       testing of the formula's behaviour. If possible, try to refrain from
#       the classical "chosing all the instances because I want to test on
#       another/all distro/s" trap: it will just add time to the testing (see
#       the discussion on #121).  As an example, the set chosen below covers
#       the most used distros families, systemd and non-systemd and the latest
#       three supported Saltstack versions with python2 and 3.
#       As for `kitchen.yml`, that should still contain all of the platforms,
#       to allow for comprehensive local testing
#       Ref: https://github.com/saltstack-formulas/template-formula/issues/118
#       Ref: https://github.com/saltstack-formulas/template-formula/issues/121
env:
  matrix:
    # - INSTANCE: default-debian-10-develop-py3
     - INSTANCE: default-ubuntu-1804-develop-py3
    # - INSTANCE: default-centos-7-develop-py3
    # - INSTANCE: default-fedora-30-develop-py3
    # - INSTANCE: default-opensuse-leap-15-develop-py3
    # - INSTANCE: default-amazonlinux-2-develop-py2
     - INSTANCE: default-debian-9-2019-2-py3
    # - INSTANCE: default-ubuntu-1804-2019-2-py3
    # - INSTANCE: default-centos-7-2019-2-py3
    # - INSTANCE: default-fedora-30-2019-2-py3
    # - INSTANCE: default-opensuse-leap-15-2019-2-py3
    # - INSTANCE: default-amazonlinux-2-2019-2-py2
    # - INSTANCE: default-debian-9-2018-3-py2
    # - INSTANCE: default-ubuntu-1604-2018-3-py2
     - INSTANCE: default-centos-7-2018-3-py2
    # - INSTANCE: default-fedora-29-2018-3-py2
    # - INSTANCE: default-opensuse-leap-15-2018-3-py2
    # - INSTANCE: default-amazonlinux-2-2018-3-py2

before_install:
  - bundle install

script:
  - bundle exec kitchen verify ${INSTANCE}
